version: "3.7"
services:
  client:
    restart: unless-stopped
    build:
      dockerfile: ../dockerfile
      context: client

  server:
    restart: unless-stopped
    build:
      dockerfile: ../dockerfile
      context: server

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/live/${HOST-host}:/etc/letsencrypt/live/host
    ports:
      - 443:443
