version: "3.7"
services:
  client:
    restart: unless-stopped
    build:
      dockerfile: ../dockerfile
      context: client
      args:
        SKIP_BUILD: SKIP
    volumes:
      - ./client/src:/app/src
    entrypoint: npm run dev

  server:
    volumes:
      - ./server/src:/app/src
    entrypoint: npx concurrently "npm run build:dev" "npm run dev"

  nginx:
    logging:
      driver: none
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 3000:3000
