version: "3.7"
services:
  server:
    restart: unless-stopped
    build:
      dockerfile: ../dockerfile
      context: server

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    ports:
      - 443:443
