version: "3.7"
services:
  next:
    build:
      args:
        SKIP_BUILD: SKIP
    volumes:
      - ./pages:/next/pages
      - ./src:/next/src
    entrypoint: npm run next:dev

  nginx:
    logging:
      driver: none
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
