version: "3.7"
services:
  next:
    build:
      args:
        SKIP_BUILD: SKIP
    volumes:
      - ./pages:/next/pages
      - ./src:/next/src
    entrypoint: node_modules/.bin/next dev

  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
