version: "3.7"
services:
  next:
    build: .
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    restart: unless-stopped

  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

volumes:
  mongodb:
