version: "3.7"
services:
  next:
    build:
      args:
        SKIP_BUILD: SKIP
    volumes:
      - ./pages:/next/pages
      - ./src:/next/src
    entrypoint: npm run next:dev

  nginx:
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  mongo-express:
    ports:
      - 8080:8081
