version: "3.7"
services:
  server:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./src:/server/src
    command: npx concurrently "npm run build:dev" "node --watch -r dotenv/config dist/index"

  nginx:
    volumes:
      - ./nginx.development.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
