name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
          submodules: recursive
      - run: cp /home/ubuntu/.env .env
      - run: docker compose -f docker-compose.yml -f docker-compose.pro.yml up -d
